class_path: acid_ddsp.synth_modules.BiquadWQFilter
init_args:
  sr: 16000
  min_w_hz: 100
  max_w_hz: 8000
  min_q: 0.7071
  max_q: 8.0
  eps: 1e-3
  modulate_log_w: true
  modulate_log_q: true
  interp_coeff: false
  filter_type: lp
